-- 회원가입 테이블 생성
CREATE TABLE MEMBER(
MEMBER_NUM NUMBER DEFAULT 0 NOT NULL,
ID VARCHAR(20) PRIMARY KEY,
PASSWORD VARCHAR(20) NOT NULL,
NAME VARCHAR(20) NOT NULL,
BIRTH DATE ,
GENDER VARCHAR(1) CHECK( GENDER = 'M' OR GENDER = 'F'),
EMAIL VARCHAR(20) UNIQUE,  -- 이메일 중복되면 안되므로 unique 추가
PHONE VARCHAR(10) NOT NULL ,
RECOMMENDER_ID VARCHAR(20) NOT NULL,
REG_DATE DATE DEFAULT SYSDATE
);

DESC MEMBER;

INSERT INTO MEMBER
VALUES(1, 'DODO12', 'ABC123', '김도연', '92/09/11', 'F', '1162004@naver.com', '23453136', 'fds2236', '22/09/05');

SELECT * FROM MEMBER;

CREATE TABLE BOARD (
    ENUM NUMBER PRIMARY KEY,  
    ENAME VARCHAR2(20) 
);
INSERT INTO BOARD VALUES(1,'자유게시판');
INSERT INTO BOARD VALUES(2,'JAVA');
INSERT INTO BOARD VALUES(3,'PYTHON');
INSERT INTO BOARD VALUES(4,'HTML');
INSERT INTO BOARD VALUES(5,'C');
INSERT INTO BOARD VALUES(6,'이벤트');
INSERT INTO BOARD VALUES(7, '공지');

SELECT * FROM BOARD;

-- 글쓰기 테이블 생성

CREATE TABLE 글쓰기 (
WRITE_NUM NUMBER NOT NULL,
WRITE_TITLE VARCHAR2(200) NOT NULL,
WRITE_CONTENTS VARCHAR2(4000),
WRITE_ID VARCHAR(20) NOT NULL,
WRITE_RDATE DATE DEFAULT SYSDATE,
WRITE_VIEWCNT NUMBER DEFAULT 0,
PUBLIC_FILE VARCHAR(1) CHECK ( PUBLIC_FILE = 'Y' OR PUBLIC_FILE = 'N'), --(공개 범위)
--COMMENT_CHK?VARCHAR(1)?CHECK ( REPLY ='Y' OR REPLY = 'N'), -- (댓글 허용)
--CHANGE_CHK?VARCHAR(1)?CHECK ( CHANGE ='Y' OR CHANGE = 'N'), --(수정 여부) 
PRIMARY KEY(WRITE_NUM)
);

-- 좋아요 싫어요 숫자 늘어나게 설정
CREATE TABLE 조하요(
LIKE_CNT NUMBER DEFAULT 0,
LIKE_NUM NUMBER REFERENCES 글쓰기(WRITE_NUM)
);

INSERT INTO 조하요 (LIKE_CNT)
VALUES (좋아요개수.NEXTVAL);

CREATE SEQUENCE 좋아요개수
START WITH 1
INCREMENT BY 1
NOMAXVALUE NOCACHE;

--좋아요 개수늘리기
SELECT 좋아요개수.NEXTVAL FROM DUAL;

--좋아요 개수확인
SELECT * FROM ALL_SEQUENCES
WHERE SEQUENCE_NAME = '좋아요개수';

COMMIT;

CREATE TABLE 시러요(
DISLIKE_CNT NUMBER DEFAULT 0,
DISLIKE_NUM NUMBER REFERENCES 글쓰기(WRITE_NUM)
);

INSERT INTO 시러요
VALUES (싫어요개수.NEXTVAL,1);

CREATE SEQUENCE 싫어요개수
START WITH 1
INCREMENT BY 1
NOMAXVALUE NOCACHE;

SELECT 싫어요개수.NEXTVAL FROM DUAL;

--싫어요 갯수확인
SELECT * FROM ALL_SEQUENCES
WHERE SEQUENCE_NAME = '싫어요개수';

--------------------------------------------------------------------

--공개범위 설정
CREATE TABLE PUBLIC_FILE (
  FILE_NO NUMBER,
  BNO VARCHAR2(100) NOT NULL,
  PUBLIC_FILE VARCHAR(1) CHECK ( PUBLIC_FILE = 'Y' OR PUBLIC_FILE = 'N')
);
COMMIT;


