-- 부모테이블, WRITE_NUM을 프라임키로 설정
CREATE TABLE PK_TABLE(
WRITE_NUM NUMBER PRIMARY KEY,
WRITE_TITLE VARCHAR2(200) NOT NULL,
WRITE_CONTENTS VARCHAR2(4000),
WRITE_ID VARCHAR(20) NOT NULL,
WRITE_RDATE DATE DEFAULT SYSDATE,
WRITE_VIEWCNT NUMBER DEFAULT 0,
WRITE_LIKE NUMBER DEFAULT 0 NOT NULL,
WRITE_DISLIKE NUMBER DEFAULT 0 NOT NULL,
PUBLIC_FILE VARCHAR(1) CHECK ( PUBLIC_FILE = 'Y' OR PUBLIC_FILE = 'N')
);

-- 자식테이블
CREATE TABLE FK_TABLE(
    WRITE_NUM NUMBER,
    CATAGORY VARCHAR2(40) CHECK(CATAGORY = '자유게시판' OR CATAGORY = 'JAVA' OR CATAGORY = 'PYTHON' OR 
						CATAGORY = 'HTML' OR CATAGORY = 'C' OR CATAGORY = '이벤트' OR
						CATAGORY = '공지'),
    WRITE_TITLE VARCHAR2(200),
    CONSTRAINT FK_CODE FOREIGN KEY(WRITE_NUM) REFERENCES PK_TABLE(WRITE_NUM)
    );