/* 연습 문제 (3) - HR 계정 */

-- 1. 커미션을 받는 사원의 이름, 직업, 부서번호, 부서명을 출력
SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;

SELECT E.FIRST_NAME, E.JOB_ID, E.DEPARTMENT_ID, D.DEPARTMENT_NAME, E.COMMISSION_PCT
    FROM EMPLOYEES E JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    AND E.COMMISSION_PCT IS NOT NULL;

-- 2. 사원이름과 부서명과 월급을 출력하는데 월급이 3000 이상인 사원을 출력
SELECT E.FIRST_NAME, D.DEPARTMENT_NAME, E.SALARY
    FROM EMPLOYEES E JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    AND SALARY >= 3000;